name: "HA OpenSpeedTest.com"
description: "Home Assistant OpenSpeedTest.com add-on!"
version: "1.0.0"
slug: "ha_openspeedtest"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  3000/tcp: 3000
  3001/tcp: 3001
image: openspeedtest/latest
